#!/usr/bin/env python3
"""
Apply Delhi speed limits (delhi_speed_limits.typ.xml) to the committed network.

The committed delhi_intersection.net.xml cannot be regenerated byte-for-byte
from build_network.py (a rebuild produces different edge IDs, which would
break the scenario route files), so the limits are patched onto the existing
network instead: netconvert reloads it (-s) with a per-edge speed override
(-e), recomputing junction-internal lanes. Edge IDs, lengths, lanes,
permissions, nodes, traffic lights and projection are unchanged.

    python networks/delhi/apply_speed_limits.py

Re-running it is a no-op once the limits are applied.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
NET_FILE = HERE / "delhi_intersection.net.xml"
LIMITS_FILE = HERE / "delhi_speed_limits.typ.xml"


def main() -> None:
    sys.path.append(os.path.join(os.environ.get("SUMO_HOME", ""), "tools"))
    import sumolib

    limits = {t.get("id"): t.get("speed") for t in ET.parse(LIMITS_FILE).getroot()}
    net = sumolib.net.readNet(str(NET_FILE))
    patch = ET.Element("edges")
    for edge in net.getEdges():
        if not edge.isSpecial() and edge.getType() in limits:
            ET.SubElement(patch, "edge", id=edge.getID(), speed=limits[edge.getType()])

    with tempfile.TemporaryDirectory() as tmp:
        patch_file = Path(tmp) / "speed_limits.edg.xml"
        out_file = Path(tmp) / "patched.net.xml"
        ET.ElementTree(patch).write(patch_file)
        subprocess.run(
            [
                sumolib.checkBinary("netconvert"),
                "-s", str(NET_FILE),
                "-e", str(patch_file),
                "-o", str(out_file),
                "--no-warnings", "true",
            ],
            check=True,
        )
        NET_FILE.write_bytes(out_file.read_bytes())
    print(f"Applied {len(patch)} edge speed limits from {LIMITS_FILE.name} to {NET_FILE.name}")


if __name__ == "__main__":
    main()
