#!/usr/bin/env python3
"""Serve the standalone route-replay demo and bundled hero-run JSON.

This server intentionally has no SUMO, TraCI, or simulation imports.  Put
frontend-ready files generated by ``export_for_frontend.py bundle`` in
``frontend_data/`` and launch with ``python3 server.py``.
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import re
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlparse


PROJECT_ROOT = Path(__file__).resolve().parent
SAFE_RUN_ID = re.compile(r"^[A-Za-z0-9_-]+$")


class DemoHandler(BaseHTTPRequestHandler):
    data_dir: Path

    def send_json(self, status: HTTPStatus, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def send_file(self, path: Path, content_type: str) -> None:
        try:
            body = path.read_bytes()
        except OSError:
            self.send_json(HTTPStatus.NOT_FOUND, {"error": "Requested file not found."})
            return
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", content_type)
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802 - required stdlib handler name
        request_path = unquote(urlparse(self.path).path)
        if request_path in {"/", "/index.html"}:
            self.send_file(PROJECT_ROOT / "index.html", "text/html; charset=utf-8")
            return

        if request_path.startswith("/api/runs/"):
            run_id = request_path.removeprefix("/api/runs/")
            self.serve_run(run_id)
            return

        # This makes the frontend's static-file fallback work with this server
        # too, while serving only JSON directly beneath the configured data dir.
        if request_path.startswith("/frontend_data/"):
            self.serve_run(request_path.removeprefix("/frontend_data/").removesuffix(".json"))
            return

        self.send_json(HTTPStatus.NOT_FOUND, {"error": "Resource not found."})

    def serve_run(self, run_id: str) -> None:
        clean_id = run_id.removesuffix(".json")
        if not SAFE_RUN_ID.fullmatch(clean_id):
            self.send_json(HTTPStatus.BAD_REQUEST, {"error": "Invalid run ID."})
            return
        candidates = [
            self.data_dir / f"{clean_id}.json",
            self.data_dir / f"hero_{clean_id}.json",
            self.data_dir / f"hero_{clean_id}_va_qpso.json",
            self.data_dir / f"{clean_id}",
        ]
        found = next((c for c in candidates if c.is_file()), None)
        if not found:
            self.send_json(
                HTTPStatus.NOT_FOUND,
                {"error": f"Run '{run_id}' not found in {self.data_dir.name}/."},
            )
            return
        self.send_file(found, "application/json; charset=utf-8")

    def log_message(self, format: str, *args: object) -> None:
        """Keep normal demo use quiet; errors remain visible in the browser."""


def main() -> None:
    parser = argparse.ArgumentParser(description="Serve the bundled route replay demo")
    parser.add_argument("--host", default="127.0.0.1", help="Host to bind (default: 127.0.0.1)")
    parser.add_argument("--port", default=8000, type=int, help="Port to bind (default: 8000)")
    parser.add_argument("--data-dir", default="frontend_data", help="Directory containing exported hero JSON")
    args = parser.parse_args()

    DemoHandler.data_dir = (PROJECT_ROOT / args.data_dir).resolve()
    server = ThreadingHTTPServer((args.host, args.port), DemoHandler)
    print(f"Route replay: http://{args.host}:{args.port} (data: {DemoHandler.data_dir})")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
